#ルールの一覧： https://qiita.com/uhooi/items/7f5d6cf2b240f60ba1ed#empty-count
#導入の参考： https://qiita.com/uhooi/items/bf888b53b4b8210108aa

#デフォルト時有効で無効にするルール
disabled_rules:
    - opening_brace # SwiftUI使ってると定義と括弧の始点が同じ行に来ないため
    - identifier_name
#デフォルト時無効で有効にするルール
opt_in_rules:
    - attributes
    - closure_end_indentation
    - closure_spacing
    - conditional_returns_on_newline
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_count
    - empty_string
    - fatal_error_message
    - identical_operands
    - legacy_random
    - literal_expression_end_indentation
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - nimble_operator
    - number_separator
    - operator_usage_whitespace
    - sorted_imports
    - switch_case_on_newline
    - toggle_bool
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

included:
    - ./BusdesKICNativeiOS

excluded:
    - ./BusdesKICNativeiOS/Generated
    
# 1行あたりの文字数制限の変更
line_length: 300

# 変数名が１文字以上なら許可に変更
identifier_name:
    min_length:
        warning: 1
